### ISSUE TITLE
catkin_make

### ISSUE THREAD

**Issue by QING-ML** [peteflorence/nanomap_ros#10]
when i catkin_make in the root of workspace, There is an error: 
The specified base path "/home/nanomap_ros" contains a package but "catkin_make" must be invoked in the root of workspace

**Comment by peteflorence** [comment]
https://answers.ros.org/question/221538/the-specified-base-path-homeruicatkin_ws-contains-a-package-but-catkin_make-must-be-invoked-in-the-root-of-workspace-how-can-i-fix-it/

**Comment by QING-ML** [comment]
Thanks, I have solve it, I should creat a new catkin_workspace/src and then git clone the project into src folder, then catkin_make in the root folder.

**Comment by peteflorence** [comment]
Great!
