### ISSUE TITLE
addPoseUpdates()

### ISSUE THREAD

**Issue by nichjang** [peteflorence/nanomap_ros#8]
We are experimenting with seeing if NanoMap could be used instead of the traditional SLAM-based navigation planning. I'm been looking at what addPoseUpdates() does but I'm still not sure (seems like it takes a path of recent poses and updates the k-d tree). Is this a necessary component and how exactly would we get that data?

Thanks

**Comment by peteflorence** [comment]
Hi there,
addPoseUpdates is not required.
The use case is for whenever new information is used to update the previous
estimate of where your previous poses were. This is the case in a sliding
window state estimator and/or some global loop closure framework.
Good luck and let me know if you have any more questions!
