### ISSUE TITLE
I DON'T 

### ISSUE THREAD

**Issue by wpv1999** [peteflorence/nanomap_ros#9]
May i start by pulling the docker into a raspberry pi and how would I do to tune this  with my pi camera?

**Comment by peteflorence** [comment]
NanoMap needs to use some sensor that has (non-zero-volume) sensing of 3D
I don't think I've ever seen anybody use a 3D sensor with a pi
I'd recommend using instead an intel NUC / Nvidia Jetson / something more up at that level of compute
